serverAddr = "meet.example.com"
serverPort = 7000

[[proxies]]
name = "meet_example_com_udp"
type = "udp"
localPort = 10000
remotePort = 10000

[[proxies]]
name = "meet_example_com_http"
type = "http"
localPort = 80
customDomains = ["meet.example.com"]

[[proxies]]
name = "meet_example_com_https"
type = "https"
localPort = 443
customDomains = ["meet.example.com"]
